// =====================================
// SLOTS DATABASE (EXPAND AS YOU GO)
// =====================================
// This is a local list for autocomplete + provider stats.
// You can keep adding to this list manually or later replace it
// with a real API-backed solution.

window.SLOTS_DB = [
    // ---------------------------------
    // PRAGMATIC PLAY
    // ---------------------------------
    { name: "Sugar Rush", provider: "Pragmatic Play" },
    { name: "Sugar Rush 1000", provider: "Pragmatic Play" },
    { name: "Sugar Rush Xmas", provider: "Pragmatic Play" },
    { name: "Gates of Olympus", provider: "Pragmatic Play" },
    { name: "Starlight Princess", provider: "Pragmatic Play" },
    { name: "Starlight Christmas", provider: "Pragmatic Play" },
    { name: "Sweet Bonanza", provider: "Pragmatic Play" },
    { name: "Sweet Bonanza Xmas", provider: "Pragmatic Play" },
    { name: "Sweet Bonanza 1000", provider: "Pragmatic Play" },
    { name: "Big Bass Bonanza", provider: "Pragmatic Play" },
    { name: "Big Bass Bonanza Megaways", provider: "Pragmatic Play" },
    { name: "Big Bass Amazon Xtreme", provider: "Pragmatic Play" },
    { name: "Big Bass Splash", provider: "Pragmatic Play" },
    { name: "Big Bass Hold & Spinner", provider: "Pragmatic Play" },
    { name: "Big Bass Xmas", provider: "Pragmatic Play" },
    { name: "Big Bass Bonanza Keeping it Reel", provider: "Pragmatic Play" },
    { name: "Big Bass Bonanza – Christmas Catch", provider: "Pragmatic Play" },
    { name: "Big Bass – Hold & Spinner Megaways", provider: "Pragmatic Play" },
    { name: "The Dog House", provider: "Pragmatic Play" },
    { name: "The Dog House Megaways", provider: "Pragmatic Play" },
    { name: "The Dog House Multihold", provider: "Pragmatic Play" },
    { name: "Bigger Bass Bonanza", provider: "Pragmatic Play" },
    { name: "Big Bass – Bonanza Keeping It Reel", provider: "Pragmatic Play" },
    { name: "Big Bass – Bonanza Splash", provider: "Pragmatic Play" },
    { name: "Big Bass – Bonanza Keeping it Reel Xmas", provider: "Pragmatic Play" },
    { name: "Wild West Gold", provider: "Pragmatic Play" },
    { name: "Wild West Duels", provider: "Pragmatic Play" },
    { name: "Wild West Gold Megaways", provider: "Pragmatic Play" },
    { name: "Sugar Supreme Powernudge", provider: "Pragmatic Play" },
    { name: "Release the Kraken", provider: "Pragmatic Play" },
    { name: "Release the Kraken 2", provider: "Pragmatic Play" },
    { name: "Fruit Party", provider: "Pragmatic Play" },
    { name: "Fruit Party 2", provider: "Pragmatic Play" },
    { name: "Gems Bonanza", provider: "Pragmatic Play" },
    { name: "Madame Destiny Megaways", provider: "Pragmatic Play" },
    { name: "Sugar Supreme", provider: "Pragmatic Play" },
    { name: "Starlight Xmas", provider: "Pragmatic Play" },
    { name: "Power of Thor Megaways", provider: "Pragmatic Play" },
    { name: "Bigger Bass Blizzard", provider: "Pragmatic Play" },
    { name: "Bigger Bass – Keeping it Reel", provider: "Pragmatic Play" },
    { name: "Barn Festival", provider: "Pragmatic Play" },
    { name: "Sugar Supreme Bonanza", provider: "Pragmatic Play" },
  
    // ---------------------------------
    // HACKSAW GAMING
    // ---------------------------------
    { name: "Steamrunners", provider: "Hacksaw Gaming" },
{ name: "Le Cowboy", provider: "Hacksaw Gaming" },
{ name: "Sun Princess", provider: "Hacksaw Gaming" },
{ name: "The Count", provider: "Hacksaw Gaming" },
{ name: "Bash Bros", provider: "Hacksaw Gaming" },
{ name: "The Wildwood Curse", provider: "Hacksaw Gaming" },
{ name: "Chaos Crew 3", provider: "Hacksaw Gaming" },
{ name: "Stormborn", provider: "Hacksaw Gaming" },
{ name: "Le Zeus", provider: "Hacksaw Gaming" },
{ name: "Tiger Legends", provider: "Hacksaw Gaming" },
{ name: "Miami Mayhem", provider: "Hacksaw Gaming" },
{ name: "Bullets and Bounty", provider: "Hacksaw Gaming" },
{ name: "Marlin Masters: The Big Haul", provider: "Hacksaw Gaming" },
{ name: "Rainbow Princess", provider: "Hacksaw Gaming" },
{ name: "Aiko and the Wind Spirit", provider: "Hacksaw Gaming" },
{ name: "The Luxe", provider: "Hacksaw Gaming" },
{ name: "Eye of Medusa", provider: "Hacksaw Gaming" },
{ name: "Invictus", provider: "Hacksaw Gaming" },
{ name: "Le King", provider: "Hacksaw Gaming" },
{ name: "Freds Food Truck", provider: "Hacksaw Gaming" },
{ name: "Booze Bash", provider: "Hacksaw Gaming" },
{ name: "Ultimate Slot of America", provider: "Hacksaw Gaming" },
{ name: "Spinman", provider: "Hacksaw Gaming" },
{ name: "Pray for Three", provider: "Hacksaw Gaming" },
{ name: "Danny Dollar", provider: "Hacksaw Gaming" },
{ name: "Rad Maxx", provider: "Hacksaw Gaming" },
{ name: "Reign of Rome", provider: "Hacksaw Gaming" },
{ name: "Fighter Pit", provider: "Hacksaw Gaming" },
{ name: "Wishbringer", provider: "Hacksaw Gaming" },
{ name: "Life and Death", provider: "Hacksaw Gaming" },
{ name: "Dorks of the Deep", provider: "Hacksaw Gaming" },
{ name: "Strength of Hercules", provider: "Hacksaw Gaming" },
{ name: "Hounds of Hell", provider: "Hacksaw Gaming" },
{ name: "FRKN Bananas", provider: "Hacksaw Gaming" },
{ name: "Marlin Masters", provider: "Hacksaw Gaming" },
{ name: "Phoenix DuelReels", provider: "Hacksaw Gaming" },
{ name: "Le Viking", provider: "Hacksaw Gaming" },
{ name: "Klowns", provider: "Hacksaw Gaming" },
{ name: "Fire my Laser", provider: "Hacksaw Gaming" },
{ name: "Donut Division", provider: "Hacksaw Gaming" },
{ name: "Shaolin Master", provider: "Hacksaw Gaming" },
{ name: "Snow Slingers", provider: "Hacksaw Gaming" },
{ name: "Duel at Dawn", provider: "Hacksaw Gaming" },
{ name: "Wings of Horus", provider: "Hacksaw Gaming" },
{ name: "Rise of Ymir", provider: "Hacksaw Gaming" },
{ name: "Get the CHEESE", provider: "Hacksaw Gaming" },
{ name: "Cloud Princess", provider: "Hacksaw Gaming" },
{ name: "Le Pharaoh", provider: "Hacksaw Gaming" },
{ name: "Evil Eyes", provider: "Hacksaw Gaming" },
{ name: "Octo Attack", provider: "Hacksaw Gaming" },
{ name: "Donny Dough", provider: "Hacksaw Gaming" },
{ name: "Dragon’s Domain", provider: "Hacksaw Gaming" },
{ name: "SixSixSix", provider: "Hacksaw Gaming" },
{ name: "Tai the Toad", provider: "Hacksaw Gaming" },
{ name: "Twisted Lab", provider: "Hacksaw Gaming" },
{ name: "Ze Zeus", provider: "Hacksaw Gaming" },
{ name: "Cursed Crypt", provider: "Hacksaw Gaming" },
{ name: "Slayers Inc", provider: "Hacksaw Gaming" },
{ name: "Jelly Slice", provider: "Hacksaw Gaming" },
{ name: "Keep’em", provider: "Hacksaw Gaming" },
{ name: "Divine Drop", provider: "Hacksaw Gaming" },
{ name: "Orb of Destiny", provider: "Hacksaw Gaming" },
{ name: "Cash Crew", provider: "Hacksaw Gaming" },
{ name: "Rusty & Curly", provider: "Hacksaw Gaming" },
{ name: "Bouncy Bombs", provider: "Hacksaw Gaming" },
{ name: "Dawn of Kings", provider: "Hacksaw Gaming" },
{ name: "Fist of Destruction", provider: "Hacksaw Gaming" },
{ name: "Beam Boys", provider: "Hacksaw Gaming" },
{ name: "Feel the Beat", provider: "Hacksaw Gaming" },
{ name: "2 Wild 2 Die", provider: "Hacksaw Gaming" },
{ name: "Dark Summoning", provider: "Hacksaw Gaming" },
{ name: "Xmas Drop", provider: "Hacksaw Gaming" },
{ name: "Immortal Desire", provider: "Hacksaw Gaming" },
{ name: "Eye of the Panda", provider: "Hacksaw Gaming" },
{ name: "Benny the Beer", provider: "Hacksaw Gaming" },
{ name: "Chaos Crew 2", provider: "Hacksaw Gaming" },
{ name: "Densho", provider: "Hacksaw Gaming" },
{ name: "Le Bandit", provider: "Hacksaw Gaming" },
{ name: "Ronin Stackways", provider: "Hacksaw Gaming" },
{ name: "Drop’em", provider: "Hacksaw Gaming" },
{ name: "Vending Machine", provider: "Hacksaw Gaming" },
{ name: "Beast Below", provider: "Hacksaw Gaming" },
{ name: "Mighty Masks", provider: "Hacksaw Gaming" },
{ name: "Temple of Torment", provider: "Hacksaw Gaming" },
{ name: "Mayan Stackways", provider: "Hacksaw Gaming" },
{ name: "Cursed Seas", provider: "Hacksaw Gaming" },
{ name: "Fear the Dark", provider: "Hacksaw Gaming" },
{ name: "Stormforged", provider: "Hacksaw Gaming" },
{ name: "Keep 'em Cool", provider: "Hacksaw Gaming" },
{ name: "Magic Piggy", provider: "Hacksaw Gaming" },
{ name: "Bloodthirst", provider: "Hacksaw Gaming" },
{ name: "Frank’s Farm", provider: "Hacksaw Gaming" },
{ name: "Rip City", provider: "Hacksaw Gaming" },
{ name: "Rotten", provider: "Hacksaw Gaming" },
{ name: "Gronk’s Gems", provider: "Hacksaw Gaming" },
{ name: "Book of Time", provider: "Hacksaw Gaming" },
{ name: "Pug Life", provider: "Hacksaw Gaming" },
{ name: "Undead Fortune", provider: "Hacksaw Gaming" },
{ name: "Break Bones", provider: "Hacksaw Gaming" },
{ name: "Alpha Eagle", provider: "Hacksaw Gaming" },
{ name: "Forest Fortune", provider: "Hacksaw Gaming" },
{ name: "Time Spinners", provider: "Hacksaw Gaming" },
{ name: "Fruit Duel", provider: "Hacksaw Gaming" },
{ name: "Dork Unit", provider: "Hacksaw Gaming" },
{ name: "Born Wild", provider: "Hacksaw Gaming" },
{ name: "Outlaws Inc.", provider: "Hacksaw Gaming" },
{ name: "Buffalo Stack’n’Sync", provider: "Hacksaw Gaming" },
{ name: "Itero", provider: "Hacksaw Gaming" },
{ name: "Hand Of Anubis", provider: "Hacksaw Gaming" },
{ name: "Gladiator Legends", provider: "Hacksaw Gaming" },
{ name: "Warrior Ways", provider: "Hacksaw Gaming" },
{ name: "Double Rainbow", provider: "Hacksaw Gaming" },
{ name: "The Bowery Boys", provider: "Hacksaw Gaming" },
{ name: "Harvest Wilds", provider: "Hacksaw Gaming" },
{ name: "King Carrot", provider: "Hacksaw Gaming" },
{ name: "Joker Bombs", provider: "Hacksaw Gaming" },
{ name: "Tasty Treats", provider: "Hacksaw Gaming" },
{ name: "Cash Quest", provider: "Hacksaw Gaming" },
{ name: "Rocket Reels", provider: "Hacksaw Gaming" },
{ name: "Toshi Video Club", provider: "Hacksaw Gaming" },
{ name: "Xpander", provider: "Hacksaw Gaming" },
{ name: "Hop'N'Pop", provider: "Hacksaw Gaming" },
{ name: "Stack'Em", provider: "Hacksaw Gaming" },

  
    // ---------------------------------
    // RELAX GAMING
    // ---------------------------------
    { name: "Money Train", provider: "Relax Gaming" },
    { name: "Money Train 2", provider: "Relax Gaming" },
    { name: "Money Train 3", provider: "Relax Gaming" },
    { name: "Money Train 4", provider: "Relax Gaming" },
    { name: "Dead Man's Trail", provider: "Relax Gaming" },
    { name: "Dead Riders Trail", provider: "Relax Gaming" },
    { name: "Temple Tumble Megaways", provider: "Relax Gaming" },
    { name: "Temple Tumble 2", provider: "Relax Gaming" },
    { name: "TNT Tumble", provider: "Relax Gaming" },
    { name: "Dead Man's Gold", provider: "Relax Gaming" },
  
    // ---------------------------------
    // NOLIMIT CITY
    // ---------------------------------
    { name: "San Quentin", provider: "NoLimit City" },
    { name: "San Quentin xWays", provider: "NoLimit City" },
    { name: "Mental", provider: "NoLimit City" },
    { name: "Tombstone", provider: "NoLimit City" },
    { name: "Tombstone RIP", provider: "NoLimit City" },
    { name: "Deadwood", provider: "NoLimit City" },
    { name: "Deadwood xNudge", provider: "NoLimit City" },
    { name: "Fire in the Hole xBomb", provider: "NoLimit City" },
    { name: "Road Rage", provider: "NoLimit City" },
    { name: "Tomb of Akhenaten", provider: "NoLimit City" },
    { name: "Misery Mining", provider: "NoLimit City" },
  
    // ---------------------------------
    // PUSH GAMING
    // ---------------------------------
    { name: "Big Bamboo", provider: "Push Gaming" },
    { name: "Razor Shark", provider: "Push Gaming" },
    { name: "Razor Returns", provider: "Push Gaming" },
    { name: "Jammin' Jars", provider: "Push Gaming" },
    { name: "Jammin' Jars 2", provider: "Push Gaming" },
    { name: "Mystery Museum", provider: "Push Gaming" },
    { name: "Wild Swarm", provider: "Push Gaming" },
    { name: "Retro Tapes", provider: "Push Gaming" },
  
    // ---------------------------------
    // BIG TIME GAMING
    // ---------------------------------
    { name: "Bonanza Megaways", provider: "Big Time Gaming" },
    { name: "Extra Chilli", provider: "Big Time Gaming" },
    { name: "Lil' Devil", provider: "Big Time Gaming" },
    { name: "Danger High Voltage", provider: "Big Time Gaming" },
    { name: "Rasputin Megaways", provider: "Big Time Gaming" },
    { name: "White Rabbit", provider: "Big Time Gaming" },
  
    // ---------------------------------
    // ELK STUDIOS
    // ---------------------------------
    { name: "Taco Brothers", provider: "ELK Studios" },
    { name: "Dead Man's Trail", provider: "ELK Studios" },
    { name: "Nitropolis", provider: "ELK Studios" },
    { name: "Nitropolis 2", provider: "ELK Studios" },
    { name: "Nitropolis 3", provider: "ELK Studios" },
    { name: "Pacific Gold", provider: "ELK Studios" },
    { name: "Tropicool", provider: "ELK Studios" },
  
    // ---------------------------------
    // PLAY'N GO
    // ---------------------------------
    { name: "Book of Dead", provider: "Play'n GO" },
    { name: "Legacy of Dead", provider: "Play'n GO" },
    { name: "Rise of Merlin", provider: "Play'n GO" },
    { name: "Reactoonz", provider: "Play'n GO" },
    { name: "Reactoonz 2", provider: "Play'n GO" },
    { name: "Moon Princess", provider: "Play'n GO" },
    { name: "Moon Princess 100", provider: "Play'n GO" },
  
    // ---------------------------------
    // QUICKSPIN
    // ---------------------------------
    { name: "Big Bad Wolf", provider: "Quickspin" },
    { name: "Big Bad Wolf Megaways", provider: "Quickspin" },
    { name: "Sakura Fortune", provider: "Quickspin" },
    { name: "Sakura Fortune 2", provider: "Quickspin" },
    { name: "Sticky Bandits", provider: "Quickspin" },
    { name: "Sticky Bandits: Trail of Blood", provider: "Quickspin" },
    { name: "Eastern Emeralds", provider: "Quickspin" },
  
    // ---------------------------------
    // BLUEPRINT GAMING
    // ---------------------------------
    { name: "The Goonies", provider: "Blueprint Gaming" },
    { name: "The Goonies Return", provider: "Blueprint Gaming" },
    { name: "Rick and Morty Megaways", provider: "Blueprint Gaming" },
    { name: "The Goonies Hey You Guys", provider: "Blueprint Gaming" },
    { name: "Buffalo Rising Megaways", provider: "Blueprint Gaming" },
    { name: "Eye of Horus", provider: "Blueprint Gaming" },
    { name: "Eye of Horus Megaways", provider: "Blueprint Gaming" },
  
    // ---------------------------------
    // OTHER POPULAR / FILLER SLOTS
    // ---------------------------------
    { name: "Book of Ra", provider: "Novomatic" },
    { name: "Book of Ra Deluxe", provider: "Novomatic" },
    { name: "Book of Shadows", provider: "NoLimit City" },
    { name: "Wanted – Dead or a Wild Xmas", provider: "Hacksaw Gaming" },
    { name: "Bonanza Billion", provider: "BGaming" },
    { name: "Sugar Bonanza", provider: "BGaming" },
    { name: "Chaos Crew Dream Drop", provider: "Hacksaw Gaming" },
    { name: "The Dog House Dice Show", provider: "Pragmatic Play" },
    { name: "Big Bass Amazon Extreme", provider: "Pragmatic Play" },
    { name: "Sugar Rush Valentine's", provider: "Pragmatic Play" },
  ];
  